Fix llvm version error
verificarlo/verificarlo pull request #226
Opened 2021-03-18 21:59 UTC by Sholde

Hello,

When I tried to use Verificarlo with llvm version 11.1.0 I see this message:
```
LLVM version up to 11.1.0 is supported
```
I think it is just one forgets.

I also add **pandas** dependency on README.

2021-03-19 08:21 UTC, pablooliveira commented
Dear @Sholde, thanks for your contribution.
The pandas dependency looks good and can be merged.

But the fix with the LLVM version is not correct. The message is correctly worded, but maybe the version check has a problem.

2021-03-19 08:22 UTC, pablooliveira requested changes
The message in ax_llvm is correct but maybe there is a problem elsewhere with the version checking.

2021-03-21 20:41 UTC, Sholde commented
Ok I will try to catch it.

2021-04-29 09:08 UTC, pablooliveira commented
After your update it seems everything is fine and we can close this PR. Could you please confirm @Sholde and close the PR if you agree ?

2021-04-29 09:10 UTC, pablooliveira commented
To fix the issue you just have to update the LLVM highest-supported version number in configure.ac. Instead of using 11.0.1 you can replace it with 11.9 for example but please check that it works and tests are successful before submitting a PR for this.

2021-04-29 10:46 UTC, Sholde commented
I just reinstall **llvm10** for work. I don't think reinstall **llvm 11.1.0** for the moment.

Else some tests don't pass in my machine even if **llvm10**. Maybe I haven't some dependencies.
But for your information all tests which passed with **llvm10**, passed with **llvm 11.1.0**.

But I wonder yet why the message specify that `LLVM version up to 11.0.1 is supported` although it is not supported 🤔.

I close this PR.

2021-04-29 10:47 UTC, closed without merging

2021-04-29 12:16 UTC, pablooliveira commented
If I understand the message you tried with llvm 11.1.0 and got the message that only "llvm up to 11.0.1 is supported" which makes sense to me because 11.1.0 > 11.0.1

2021-04-29 12:20 UTC, Sholde commented
Yes but verificarlo support until llvm 11.0.1. So I should have "llvm up to 11.0.1 is not supported" I think. Because the configuration script crash at this time.

2021-04-29 12:29 UTC, pablooliveira commented
No, what the message is telling you is the maximum LLVM version that we support. So in my opinion the message is correct. Thanks for the report though !

2021-04-29 12:33 UTC, Sholde commented
Oh yes, I think I need to improve my english. Sorry ^^.