Deterministic backends and asserts system for vfc_ci
verificarlo/verificarlo pull request #271
Opened 2021-07-16 08:06 UTC by PurplePachyderm

This PR brings two important features for Verificarlo CI : 

- **Support for deterministic backends** (such as VPREC) : if a backend is considered deterministic, a large part of the data processing will be ignored (computation of significant digits, etc ...), and results from this backend will be shown separately in the report.
- **Asserts system** : Probes can now optionally be linked with an "assert". This is corresponds to an accuracy target for the variable, which will be checked in preprocessing. Asserts can be used with both deterministic and non-deterministic backends, and can be of absolute or relative type. For each case, the way to validate the probe is different.

Documentation has also been updated to explain those features more in details.

2021-07-19 08:24 UTC, pablooliveira commented on src/common/vfc_probes.c
> +  for (int i = 0; i < probes->map->capacity; i++) {
Better use `size_t`.

2021-07-19 08:24 UTC, pablooliveira commented on doc/06-Postprocessing.md
> +|Deterministic|IEEE value -  Backend value < Target|(IEEE value -  Backend value) / IEEE value < Target
Please include the absolute values

2021-07-19 08:24 UTC, pablooliveira commented on doc/06-Postprocessing.md
> +int vfc_probe_assert(vfc_probes *probes, char *testName, char *varName,
Rename `vfc_check` or `vfc_check_relative` ?

2021-07-19 08:25 UTC, titeup reviewed
Can we consider exit on failure for deterministic/(mca)sunchronous backend where we can determine it at runtime? I some complex code this could also avoid wasting costly execution.

2021-07-19 08:25 UTC, titeup commented on src/common/vfc_probes.c
> -  for (size_t i = 0; i < probes->map->capacity; i++) {
why?

2021-07-19 08:25 UTC, titeup commented on src/common/vfc_probes.c
> -  for (size_t i = 0; i < probes->map->capacity; i++) {
Why?

2021-07-19 08:25 UTC, titeup commented on src/common/vfc_probes.c
> +int vfc_probe_assert(vfc_probes *probes, char *testName, char *varName,
naming? assert may be missleding since we do not abort

2021-07-20 11:56 UTC, pablooliveira requested changes
LGTM. Please fix some typos in the documentation and this is good to merge.

2021-07-20 11:56 UTC, pablooliveira commented on doc/06-Postprocessing.md
> +// Similar to vfc_probe, but with an optional accuracy threshold (absolute
absolute -> relative

2021-07-20 11:56 UTC, pablooliveira commented on doc/06-Postprocessing.md
> +inderior to the accuracy threshold for the probe to pass (or inferior to the
inderior -> inferior

2021-07-20 11:56 UTC, pablooliveira commented on doc/06-Postprocessing.md
> +But in the case of a deterministic backend, it is impossible to compute the standard
"it is impossible to compute the standard deviation" -> "the standard deviation is undefined"

2021-07-20 11:56 UTC, pablooliveira commented on doc/06-Postprocessing.md
> +deviation and the average of the probe to estimate the error. Instead , the
Instead , -> Instead,

2021-07-22 07:59 UTC, pablooliveira approved these changes
LGTM :tada:

2021-07-22 08:30 UTC, merged