fix compatibility issues with llvm 15
verificarlo/verificarlo pull request #302
Opened 2022-05-04 09:53 UTC by vincentAlba

VectorType can't access GetNumElements without being cast to FixedVectorType since llvm 13
For now the code raise an error if Scalable vector are used

The following test also fail in the current llvm version :
8,9,12,19,34

2022-05-04 11:28 UTC, pablooliveira commented
Thanks @vincentAlba ! Nice work.

Before merging, we will need to look into fixes for the failing tests.
Also the linter is failing some tests; could you please fix the formatting of your patch by running clang-format (default arguments) on the .c / .cpp files you changed ?

2022-05-04 11:36 UTC, pablooliveira commented
I see that the command ` -enable-new-pm=0 ` which is required for retro-compatibility in new LLVMs is not supported in LLVM 7. I think we should add this option conditionally depending on the LLVM version.

2022-06-28 17:17 UTC, titeup requested changes
Please change the test to version 13 (and merge and rebase with the latest master), otherwise it looks good.
Thanks for your useful contribution!

2022-06-28 17:17 UTC, titeup commented on verificarlo.in.in
> +            if llvm_version >= 15:
new pass manger start at 13. I tested your code with LLVM 13 and it works fine.

2022-06-28 17:17 UTC, titeup commented on verificarlo.in.in
> +        if llvm_version >= 15:
new pass manger start at 13. I tested your code with LLVM 13 and it works fine.

2022-07-01 09:21 UTC, pablooliveira commented
@vincentAlba all tests are now passing. The failing tests were unrelated to your patch (#305) and have been fixed.

If you implement the two changes requested: 

- activate the `enable-new-pm` option conditionally depending on the LLVM version.

- change the llvm_version test to 13 as suggested by @titeup 

we can merge this :tada:

2022-07-01 09:25 UTC, pablooliveira requested changes

2022-08-29 09:51 UTC, pablooliveira commented on verificarlo.in.in
> +        if int(llvm_version) >= 13:
```suggestion
        # For LLVM >= 13 we fallback to the legacy pass manager
        if int(llvm_version) >= 13:
```

2022-08-29 09:52 UTC, pablooliveira approved these changes

2022-08-29 09:55 UTC, pablooliveira commented
This looks good @vincentAlba, merging, thanks for the contribution.
Unrelated but could you please open a PR with the new usercall to change precision in different parts of the code we discussed together ? :-)

2022-08-29 10:01 UTC, merged